### PR TITLE
Add rackup instead of rack

### PR DESCRIPTION
**Pull request by rus-max**

### CODE REVIEW

**Comment by andrcuns** [comment]
For the most part it's a duplicate of https://github.com/arturictus/sidekiq_alive/pull/75

There is a comment which describes why this hasn't been updated. Closing this.

**Comment by rus-max** [comment]
After upgrade rack to 3.0.8
```
Failures:

  1) SidekiqAlive::Server#run! runs the handler with sidekiq_alive logger, host and no access logs
     Failure/Error: before { allow(Rack::Handler).to(receive(:get).with("webrick").and_return(fake_webrick)) }
     
     LoadError:
       cannot load such file -- rack/handler
     # ./spec/server_spec.rb:14:in `block (3 levels) in <top (required)>'
```
Because Rack::Server, Rack::Handler were removed in new [release](https://github.com/rack/rack/blob/main/CHANGELOG.md#300beta1---2022-08-08) to separate gem [rackup](https://github.com/rack/rackup) and are [deprecated](https://github.com/rack/rackup/blob/eaea24a3d64a1b117df943a9d06779e659bb61af/lib/rack/handler.rb) for use.

**Comment by andrcuns** [comment]
@rus-max I know, and here is a comment on why we can't upgrade it yet: https://github.com/arturictus/sidekiq_alive/pull/75#issuecomment-1363308683

**Comment by rus-max** [comment]
You can release a new version with rackup and it will not affect rails applications in any way. This will be provided by rack dependencies

**Comment by andrcuns** [comment]
It will. [actionpack](https://rubygems.org/gems/actionpack) has a version restriction set to `~> 2.0, >= 2.2.4` for `rack` and `rackup` requires `rack` to be `>= 3 `. This will create a conflict.

**Pull request closed without merging**
