### PR TITLE
Introduces host option

### PR DESCRIPTION
**Pull request by caioalonso**
I needed a way to customize the host option to make the server bind to a unix socket instead of `0.0.0.0`.

### CODE REVIEW

**Review by arturictus — CHANGES_REQUESTED** [review]
Hi @caioalonso,
Thanks for your PR.
Can you add documentation here https://github.com/arturictus/sidekiq_alive#options?
Once done is ready to be merged

**Comment by caioalonso** [comment]
Sure, @arturictus. Done.

**Review by arturictus — APPROVED** [review]

**Comment by arturictus** [comment]
Thanks!

**Comment by arturictus** [comment]
Thanks!

**Comment by arturictus** [comment]
Released on version 2.0.5 :partying_face:

**Pull request merged**
