### PR TITLE
Leifcr master

### PR DESCRIPTION
**Pull request by arturictus**

### CODE REVIEW

**Comment by arturictus** [comment]
Hi @leifcr ,
Thanks for your PR.
I'm working from your branch. Testing it and making some changes

**Comment by leifcr** [comment]
@arturictus Thanks for merging and fixing the ttl issue. Good catch!

**Comment by leifcr** [comment]
When removing the delay between hosts, it will end up looping indefinitely when running on a high number of hosts. I tested on 10 without delay, and it was on rare occasions that the correct worker picked up the correct workload. Most will probably just run 1 worker though, so it should be fine.

**Comment by arturictus** [comment]
> When removing the delay between hosts, it will end up looping indefinitely when running on a high number of hosts. I tested on 10 without delay, and it was on rare occasions that the correct worker picked up the correct workload. Most will probably just run 1 worker though, so it should be fine.

I'm implementing a new aproach #23 
Each instance will create it's own queue and we will not need to wait for the right instance to take it.

**Comment by arturictus** [comment]
I reset the default delay between hosts to 1

**Pull request merged**
